### PR TITLE
Use ydiff as a script instead of a module

### PR DESCRIPTION
**Pull request by ymattw**
Ydiff is not supposed to be used as a module, the recent new option --theme breaks the usage of markup_to_pager as described in https://github.com/ymattw/ydiff/issues/124.

It would be nice to move away from the current usage to pipe the texts to diff to the script directly.

The program is installed as part of the requirements.txt of patroni, so it must be available in $PATH same as patroni (usually installed in /usr/local/bin).

### CODE REVIEW

**Comment by CyberDem0n** [comment]
Hi @ymattw, thank you for a suggestion.
Unfortunately it doesn't work for us, because at least Debian/Ubuntu don't have python3-ydiff package, and they use python3-cdiff as drop-in replacement.

Last time I just forgot to modify requirements.txt and limit the upper version to avoid future problems like this one. Now it will be addressed in #3216.

However, there is yet another problem with ydiff.
You publish it as it is supporting python>=3.3: https://github.com/ymattw/ydiff/blob/2616f39f0764fa68afa8c0e5f2cfbec4ad4d2fd7/setup.py#L34
But, it doesn't work even with python 3.7, because of: https://github.com/ymattw/ydiff/blob/2616f39f0764fa68afa8c0e5f2cfbec4ad4d2fd7/ydiff.py#L439
The sum() function could be used with the `start` argument as a keyword only starting from python 3.8.

**Comment by ymattw** [comment]
Hi! I don't understand, since ydiff is imported by ctl.py, whatever environment the ctl.py script runs must already contain ydiff as a dependency. Did I miss something?

Also thanks for pointing out the sum() compatibility issue, I will fix it and release a patch version.

**Comment by CyberDem0n** [comment]
Deb packages are not relying on requirements.txt and maintain their own dependencies.
The way it currently works - if import of ydiff fails, we are making an attempt to import cdiff: https://github.com/patroni/patroni/pull/3214/files#diff-9dada8f509128404d7027246ac9622d2484fc77758c6a4af9dc7cc8c081d9fffL54

**Comment by ymattw** [comment]
Thanks for the explanation.  I think the long term solution is still migrating away from using ydiff as a library.  Every time ydiff releases a version with a new CLI option will break patroni. I will file an issue in your repo to track it.

FYI ydiff-1.4.2 is just released with the compatibility fix for Python 3.3.

**Pull request closed without merging**
